[package]
name = "upscale-rs"
version = "0.2.3"
description = "A Tauri based GUI app that upscale images using Real-ESRGAN model."
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
license = "MIT"
repository = "https://github.com/OLoKo64/upscale-rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
strip = true

[build-dependencies]
tauri-build = { version = "1.5.3", features = [] }

[dependencies]
serde_json = "1.0.121"
serde = { version = "1.0.204", features = ["derive"] }
tauri = { version = "1.7.1", features = ["dialog-all", "fs-all", "notification-all", "os-all", "shell-all", "window-all"] }
base64 = "0.22.1"
dirs = "5.0.1"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
